### ISSUE TITLE
check in Dependencies  / remove fixed symlinks / License

### ISSUE THREAD

**Issue by alexanderadam** [Heaven31415/CrystalSpaceShooter#1]
Wow, this looks awesome!

Would it be possible to check in the `shard` files and remove / replace the symlinks pointing to `/home/marcel/Crystal/…`? Therefore other people could build it as well.

Additionally it would be nice if you would add a license file.

Dzięki!

**Comment by Heaven31415** [comment]
Hey, I'm glad you like it. I made this project to test out crystal and I'm currently working on something else, but when I'll have a moment I'm going to fix issues you have mentioned, thanks for interest.

**Comment by faustinoaq** [comment]
This is very nice! :+1: 

![vokoscreen-2018-07-07_12-42-52](https://user-images.githubusercontent.com/3067335/42413337-79ef64ec-81e3-11e8-999c-c3b97c218748.gif)

Would be interesting to use travis to deploy stand-alone binaries to linux and macOS, WDYT?

**Comment by Heaven31415** [comment]
Hey, thank you very much for interest in my project! It was a mistake to add license so late, however I'm glad I fixed it.

It's really cool that you managed to build it and run successfully. I think it would be a great idea to deploy those binaries using travis. I just need to read a little bit about how to do that, maybe you can point in me the right direction?

**Comment by faustinoaq** [comment]
Maybe we can use a deploy config like this: https://github.com/crystal-lang-tools/scry/blob/master/.travis.yml

**Comment by Heaven31415** [comment]
Thanks for help, there is something I would like to share. Right now I'm working on a gui designer and I wanted to show a video of it: [video](https://www.youtube.com/watch?v=j9b0ByeE8SA&feature=youtu.be).

**Comment by alexanderadam** [comment]
@Heaven31415 awesome, that's a neat idea!

**Comment by Heaven31415** [comment]
Hey, writing about another update in case someone is interested in project.

I have significantly improved my GUI Designer, which is working like this:
- you create widgets by creating files (one file per one widget right now) with specific extension, for example **_test.button_** will create a new button widget.
- when you run designer, already created files are automatically loaded. If they have invalid content or something is wrong with them, designer will tell you about this.
- you can create new files during program execution and designer will see them and try to load them, same goes with deleting files, if you delete something it will be automatically unloaded.
- right now I only have two widget types: button and label, however I also have some old slider, which I need to convert to new system.
- widgets have many properties which you can change at runtime and program will automatically load those changes or inform you of error if something bad happens, you can change colours, sizes, layers and transformations (positions, rotations, scales).

There is also another demo: [demo](https://youtu.be/Fs7hienXUjA)

**Comment by Heaven31415** [comment]
License is already added, I have removed fixed symlink in 5b128853c2287bfb057d9f2fdd8b495657ee2d58 and moved voidcsfml library files into project folder. Right now I'm closing this issue, I will work in the nearest future to make it easier for someone else to build this project.
